// <auto-generated />
using System;
using EFGetStarted.AspNetCore.ExistingDb.Models1;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EFGetStarted.AspNetCore.ExistingDb.Migrations
{
    [DbContext(typeof(Database3Context))]
    [Migration("20181005091937_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EFGetStarted.AspNetCore.ExistingDb.Models1.Haandvaerker", b =>
                {
                    b.Property<int>("HaandvaerkerId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Ansaettelsedato")
                        .HasColumnType("date");

                    b.Property<string>("Efternavn")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Fagomraade")
                        .HasMaxLength(50);

                    b.Property<string>("Fornavn")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("HaandvaerkerId");

                    b.ToTable("Haandvaerker");
                });

            modelBuilder.Entity("EFGetStarted.AspNetCore.ExistingDb.Models1.Vaerktoej", b =>
                {
                    b.Property<long>("VaerktoejsId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Anskaffet")
                        .HasColumnType("date");

                    b.Property<string>("Fabrikat");

                    b.Property<int?>("LiggerIvtk")
                        .HasColumnName("LiggerIVTK");

                    b.Property<string>("Model")
                        .HasMaxLength(50);

                    b.Property<string>("Serienr")
                        .HasMaxLength(50);

                    b.Property<string>("Type")
                        .HasMaxLength(50);

                    b.HasKey("VaerktoejsId");

                    b.HasIndex("LiggerIvtk");

                    b.ToTable("Vaerktoej");
                });

            modelBuilder.Entity("EFGetStarted.AspNetCore.ExistingDb.Models1.Vaerktoejskasse", b =>
                {
                    b.Property<int>("VkasseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("VKasseId")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Anskaffet")
                        .HasColumnType("date");

                    b.Property<int?>("EjesAf");

                    b.Property<string>("Fabrikat")
                        .HasMaxLength(50);

                    b.Property<string>("Farve");

                    b.Property<string>("Model")
                        .HasMaxLength(50);

                    b.Property<string>("Serienummer")
                        .HasMaxLength(50);

                    b.HasKey("VkasseId");

                    b.HasIndex("EjesAf");

                    b.ToTable("Vaerktoejskasse");
                });

            modelBuilder.Entity("EFGetStarted.AspNetCore.ExistingDb.Models1.Vaerktoej", b =>
                {
                    b.HasOne("EFGetStarted.AspNetCore.ExistingDb.Models1.Vaerktoejskasse", "LiggerIvtkNavigation")
                        .WithMany("Vaerktoej")
                        .HasForeignKey("LiggerIvtk")
                        .HasConstraintName("FK_Vaerktoej_Vaerktsejskasse");
                });

            modelBuilder.Entity("EFGetStarted.AspNetCore.ExistingDb.Models1.Vaerktoejskasse", b =>
                {
                    b.HasOne("EFGetStarted.AspNetCore.ExistingDb.Models1.Haandvaerker", "EjesAfNavigation")
                        .WithMany("Vaerktoejskasse")
                        .HasForeignKey("EjesAf")
                        .HasConstraintName("FK_Vaerktoejskasse_ToHaandvaerker");
                });
#pragma warning restore 612, 618
        }
    }
}
