// <auto-generated />
using System;
using EFE18Demo4.AspNetCore.ExistingDbMigration.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EFE18Demo4.AspNetCore.ExistingDbMigration.Migrations
{
    [DbContext(typeof(CraftManDBContext))]
    [Migration("20181026101514_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EFE18Demo4.AspNetCore.ExistingDbMigration.Models.Haandvaerker", b =>
                {
                    b.Property<int>("HåndværkerId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Ansættelsedato")
                        .HasColumnType("date");

                    b.Property<string>("Efternavn")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Fagområde")
                        .HasMaxLength(50);

                    b.Property<string>("Fornavn")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("HåndværkerId");

                    b.ToTable("Haandvaerker");
                });

            modelBuilder.Entity("EFE18Demo4.AspNetCore.ExistingDbMigration.Models.Værktøj", b =>
                {
                    b.Property<long>("VærktøjsId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Vtanskaffet")
                        .HasColumnName("VTAnskaffet")
                        .HasColumnType("date");

                    b.Property<string>("Vtfabrikat")
                        .HasColumnName("VTFabrikat");

                    b.Property<int?>("Vtkid")
                        .HasColumnName("VTKId");

                    b.Property<string>("Vtmodel")
                        .HasColumnName("VTModel")
                        .HasMaxLength(50);

                    b.Property<string>("Vtserienr")
                        .HasColumnName("VTSerienr")
                        .HasMaxLength(50);

                    b.Property<string>("Vttype")
                        .HasColumnName("VTType")
                        .HasMaxLength(50);

                    b.HasKey("VærktøjsId");

                    b.HasIndex("Vtkid");

                    b.ToTable("Vaerktoej");
                });

            modelBuilder.Entity("EFE18Demo4.AspNetCore.ExistingDbMigration.Models.Vaerktoejskasse", b =>
                {
                    b.Property<int>("VkasseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("VKasseId")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("HåndværkerId")
                        .HasColumnName("HåndværkerID");

                    b.Property<DateTime>("Vtkanskaffet")
                        .HasColumnName("VTKAnskaffet")
                        .HasColumnType("date");

                    b.Property<string>("Vtkfabrikat")
                        .HasColumnName("VTKFabrikat")
                        .HasMaxLength(50);

                    b.Property<string>("Vtkfarve")
                        .HasColumnName("VTKFarve");

                    b.Property<string>("Vtkmodel")
                        .HasColumnName("VTKModel")
                        .HasMaxLength(50);

                    b.Property<string>("Vtkserienummer")
                        .HasColumnName("VTKSerienummer")
                        .HasMaxLength(50);

                    b.HasKey("VkasseId");

                    b.HasIndex("HåndværkerId");

                    b.ToTable("Vaerktoejskasse");
                });

            modelBuilder.Entity("EFE18Demo4.AspNetCore.ExistingDbMigration.Models.Værktøj", b =>
                {
                    b.HasOne("EFE18Demo4.AspNetCore.ExistingDbMigration.Models.Vaerktoejskasse", "Vtk")
                        .WithMany("Værktøj")
                        .HasForeignKey("Vtkid")
                        .HasConstraintName("FK_Værktøj_Værktøjskasse");
                });

            modelBuilder.Entity("EFE18Demo4.AspNetCore.ExistingDbMigration.Models.Vaerktoejskasse", b =>
                {
                    b.HasOne("EFE18Demo4.AspNetCore.ExistingDbMigration.Models.Haandvaerker", "Haandvaerker")
                        .WithMany("Vaerktoejskasse")
                        .HasForeignKey("HåndværkerId")
                        .HasConstraintName("FK_Værktøjskasse_ToHåndværker");
                });
#pragma warning restore 612, 618
        }
    }
}
