// <auto-generated />
using System;
using EFGetStarted.AspNetCore.ExistingDbMigration.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EFGetStarted.AspNetCore.ExistingDbMigration.Migrations
{
    [DbContext(typeof(Database5Context))]
    [Migration("20181005105828_Initial-RemoveDKNaming-HVVTKVT")]
    partial class InitialRemoveDKNamingHVVTKVT
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EFGetStarted.AspNetCore.ExistingDbMigration.Models.Haandvaerker", b =>
                {
                    b.Property<int>("HaandvaerkerId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("HVAnsaettelsedato")
                        .HasColumnType("date");

                    b.Property<string>("HVEfternavn")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("HVFagomraade")
                        .HasMaxLength(50);

                    b.Property<string>("HVFornavn")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("HaandvaerkerId");

                    b.ToTable("Haandvaerker");
                });

            modelBuilder.Entity("EFGetStarted.AspNetCore.ExistingDbMigration.Models.Vaerktoej", b =>
                {
                    b.Property<long>("VTId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("LiggerIvtk")
                        .HasColumnName("LiggerIVTK");

                    b.Property<DateTime>("VTAnskaffet")
                        .HasColumnType("date");

                    b.Property<string>("VTFabrikat");

                    b.Property<string>("VTModel")
                        .HasMaxLength(50);

                    b.Property<string>("VTSerienr")
                        .HasMaxLength(50);

                    b.Property<string>("VTType")
                        .HasMaxLength(50);

                    b.HasKey("VTId");

                    b.HasIndex("LiggerIvtk");

                    b.ToTable("Vaerktoej");
                });

            modelBuilder.Entity("EFGetStarted.AspNetCore.ExistingDbMigration.Models.Vaerktoejskasse", b =>
                {
                    b.Property<int>("VTKId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("VKasseId")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("VTKAnskaffet")
                        .HasColumnType("date");

                    b.Property<int?>("VTKEjesAf");

                    b.Property<string>("VTKFabrikat")
                        .HasMaxLength(50);

                    b.Property<string>("VTKFarve");

                    b.Property<string>("VTKModel")
                        .HasMaxLength(50);

                    b.Property<string>("VTKSerienummer")
                        .HasMaxLength(50);

                    b.HasKey("VTKId");

                    b.HasIndex("VTKEjesAf");

                    b.ToTable("Vaerktoejskasse");
                });

            modelBuilder.Entity("EFGetStarted.AspNetCore.ExistingDbMigration.Models.Vaerktoej", b =>
                {
                    b.HasOne("EFGetStarted.AspNetCore.ExistingDbMigration.Models.Vaerktoejskasse", "LiggerIvtkNavigation")
                        .WithMany("Vaerktoej")
                        .HasForeignKey("LiggerIvtk")
                        .HasConstraintName("FK_Vaerktoej_Vaerktsejskasse");
                });

            modelBuilder.Entity("EFGetStarted.AspNetCore.ExistingDbMigration.Models.Vaerktoejskasse", b =>
                {
                    b.HasOne("EFGetStarted.AspNetCore.ExistingDbMigration.Models.Haandvaerker", "EjesAfNavigation")
                        .WithMany("Vaerktoejskasse")
                        .HasForeignKey("VTKEjesAf")
                        .HasConstraintName("FK_Vaerktoejskasse_ToHaandvaerker");
                });
#pragma warning restore 612, 618
        }
    }
}
